language: android

jdk:
  - oraclejdk7
  - oraclejdk8

android:
  components:
    - android-23
    - build-tools-23.0.1
    - sys-img-armeabi-v7a-android-21
    - extra-android-m2repository
    - platform-tools

before_install:
  - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
  - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
  - export JAVA_HOME=$JAVA7_HOME

script:
  - ./gradlew assembleDebug test